#github/workflows/deploy.yml
name: Deploy Pipeline
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy AWS Infrastructure
        run: |
          pip install -r requirements.txt
          cdk deploy --require-approval never